//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_26.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donation
    {

        public int Donation_id { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = " Ssn is required")]
        public string Donor_Ssn { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = " Blood type is required")]
        public string bloodtype { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = " Last donation date is required")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime LastDonationDate { get; set; }

        public virtual Donor Donor { get; set; }
    }
}
