//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_26.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Donor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donor()
        {
            this.BloodBags = new HashSet<BloodBag>();
            this.Donations = new HashSet<Donation>();
        }

        [Required(AllowEmptyStrings = false, ErrorMessage = "Ssn required")]
        public string DSsn { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "First name required")]
        public string Fname { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Second name required")]
        public string Mname { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Last name required")]
        public string Lname { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = " Email is required")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Country required")]
        public string country { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "city required")]
        public string city { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Your Gender is required")]
        public string sex { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "First name required")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime birthday { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Phone number is required")]
        public string phone { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Choose your blood type")]
        public string bloodtype { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        /*[Required(AllowEmptyStrings = false, ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "the Confirmation password doesn't match the password")]
        public string ConfirmPassword { get; set; }*/



        public bool IsEmailVerify { get; set; }
        public System.Guid ActivationCode { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodBag> BloodBags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donation> Donations { get; set; }
    }
}
