//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_26.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Staff
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Staff Ssn is required")]
        public string Staff_Ssn { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Staff first name is required")]
        public string Fname { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Staff second name is required")]
        public string Mname { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Staff last name is required")]
        public string Lname { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Staff phone is required")]
        public string phone { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = " Email is required")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }



        [Required(AllowEmptyStrings = false, ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}
