//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_26.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.BloodBanks = new HashSet<BloodBank>();
        }
    
        public int Stock_Id { get; set; }
        public string Stock_name { get; set; }
        public int A_ { get; set; }
        public int A_1 { get; set; }
        public int B_ { get; set; }
        public int B_1 { get; set; }
        public int AB_ { get; set; }
        public int AB_1 { get; set; }
        public int O_ { get; set; }
        public int A_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloodBank> BloodBanks { get; set; }
    }
}
